version: '3.3'
services:
  flightapp_backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: blah
    restart: always
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=sEcRET_pASSw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=flightapp_db
    volumes:
      - db_data:/var/lib/postgresql/data        

volumes:
  db_data:
