basePath: /
consumes:
- application/json
definitions:
  CalculateFeeRequest:
    properties:
      cancellation:
        type: boolean
        x-go-name: Cancellation
      delay:
        type: boolean
        x-go-name: Delay
      flight_number:
        type: string
        x-go-name: FlightNumber
      ticket_price:
        format: float
        type: number
        x-go-name: TicketPrice
    type: object
    x-go-package: flight_app/app/flightaware_api
  CalculateFeeResponse:
    properties:
      fee:
        format: float
        type: number
        x-go-name: Fee
    type: object
    x-go-package: flight_app/app/flightaware_api
  ContractsInfo:
    properties:
      flight_number:
        type: string
        x-go-name: FlightNumber
      reward:
        format: float
        type: number
        x-go-name: Reward
      status:
        type: string
        x-go-name: Status
    type: object
    x-go-package: flight_app/app/contract
  CreateContractRequest:
    properties:
      cancellation:
        type: boolean
        x-go-name: Cancellation
      delay:
        type: boolean
        x-go-name: Delay
      flight_number:
        type: string
        x-go-name: FlightNumber
      ticket_price:
        format: float
        type: number
        x-go-name: TicketPrice
      user_id:
        type: string
        x-go-name: UserID
    type: object
    x-go-package: flight_app/app/contract
  CreateContractResponse:
    properties:
      contract_id:
        format: int64
        type: integer
        x-go-name: ContractID
      fee:
        format: float
        type: number
        x-go-name: Fee
    type: object
    x-go-package: flight_app/app/contract
  GetContractsReq:
    properties:
      user_id:
        type: string
        x-go-name: UserID
    type: object
    x-go-package: flight_app/app/contract
host: https://safe-beyond-32265.herokuapp.com/
info:
  description: Documentation of our flight_app API.
  title: flight_app.
  version: 1.0.0
paths:
  /api/calculate:
    post:
      operationId: idOfCalculateEndpoint
      parameters:
      - description: Flight information.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/CalculateFeeRequest'
      responses:
        "200":
          $ref: '#/responses/calculateResponse'
      summary: Calculate returns calculated fee.
      tags:
      - Query
  /api/contract/create:
    post:
      operationId: idOfContractCreateEndpoint
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/CreateContractRequest'
      responses:
        "200":
          $ref: '#/responses/createContractResponse'
      summary: Contract create returns fee and contractID.
      tags:
      - Query
  /api/contracts:
    post:
      description: GetContracts returns contracts of specified user
      operationId: idOfGetContractEndpoint
      parameters:
      - in: body
        name: Body
        schema:
          $ref: '#/definitions/GetContractsReq'
      responses:
        "200":
          description: ContractsInfo
          schema:
            items:
              $ref: '#/definitions/ContractsInfo'
            type: array
      tags:
      - Query
produces:
- application/json
responses:
  calculateResponse:
    description: Fee calculated on the basis of flight data.
    schema:
      $ref: '#/definitions/CalculateFeeResponse'
  createContractResponse:
    description: Contracts returns with current status and paid reward
    schema:
      $ref: '#/definitions/CreateContractResponse'
      items:
        $ref: '#/definitions/ContractsInfo'
      type: array
schemes:
- http
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
