loglevel = "debug"
listen = "127.0.0.1"
db_url = "host=localhost dbname=postgres user=postgres password=123456 sslmode=disable"
aeroapi_username = "kyulevemil"
aeroapi_apikey = "84ed2fbe7b1ff0cd96f240905758257595822df1"
client_id = "AXkGcf3pZCHgBARXg-s_nkPDSriJ7bf7d2w9_bg7cyLqHEhBCik_ycNOign5mgleV47P-VPKNNu5hZ1K"
secret_id = "ENsUOuzF49FYeX10HrLFtcUBXGPvl-NzPl8zieiLW04R5vcWPHIdUAARV8JMN0lwy1FPQjDT6iTwiP6H"