loglevel = "debug"
listen = "127.0.0.1"
db_url = "postgres://vyacheslav:1234@localhost:5432/flightapp_backend?sslmode=disable"
aeroapi_username = "kyulevemil"
aeroapi_apikey = "84ed2fbe7b1ff0cd96f240905758257595822df1"
client_id = "<paypal_client_id>"
secret_id = "<paypal_secret_id>"
solana_fee_payer_pk = "<solana_fee_payer_private_key>"
program_id = "<solana_smart_contract_id>"