loglevel = "debug"
listen = "127.0.0.1"
db_url = "db_url"
aeroapi_username = "<your_username>"
aeroapi_apikey = "<your_api_key>"
client_id = "<paypal_client_id>"
secret_id = "<paypal_secret_id>"
solana_fee_payer_pk = "<solana_fee_payer_private_key>"
program_id = "<solana_smart_contract_id>"