loglevel = "debug"
listen = "127.0.0.1:8089"
db_url = "<db url>"
aeroapi_username = "<your_username>"
aeroapi_apikey = "<your_api_key>"
client_id = "AXkGcf3pZCHgBARXg-s_nkPDSriJ7bf7d2w9_bg7cyLqHEhBCik_ycNOign5mgleV47P-VPKNNu5hZ1K"
secret_id = "ENsUOuzF49FYeX10HrLFtcUBXGPvl-NzPl8zieiLW04R5vcWPHIdUAARV8JMN0lwy1FPQjDT6iTwiP6H"