loglevel = "debug"
listen = "127.0.0.1"
db_url = ""
aeroapi_username = ""
aeroapi_apikey = ""
client_id = ""
secret_id = ""
solana_fee_payer_pk = "<solana_fee_payer_private_key>"
program_id = "<solana_smart_contract_id>"