loglevel = "debug"
listen = "127.0.0.1"
db_url = "postgres://pjcknmgtzhsmok:9bfd98ae4e5034c6e8cac32173948bef0dca3222af6b04dc7491064f327be9e5@ec2-35-153-91-18.compute-1.amazonaws.com:5432/de9eoebtcrs2p0"
aeroapi_username = "kyulevemil"
aeroapi_apikey = "84ed2fbe7b1ff0cd96f240905758257595822df1"
client_id = "AXkGcf3pZCHgBARXg-s_nkPDSriJ7bf7d2w9_bg7cyLqHEhBCik_ycNOign5mgleV47P-VPKNNu5hZ1K"
secret_id = "ENsUOuzF49FYeX10HrLFtcUBXGPvl-NzPl8zieiLW04R5vcWPHIdUAARV8JMN0lwy1FPQjDT6iTwiP6H"
solana_fee_payer_pk = "5nm33SPTQvKkUgaG8ZbvadWnPVS5YjAF53BGgeueMZavVCLdnpNF5fz1sJQouVn9weV7ikJbDWYHUAtMMhFmG3Df"
program_id = "63vtYs6fshEL7FWsrRQ2LXE4nN4NMsGxkJ1BnUwraBeW"