loglevel = "debug"
listen = "127.0.0.1"
db_url = "host=localhost dbname=postgres user=postgres password=123456 sslmode=disable"
aeroapi_username = "kyulevemil"
aeroapi_apikey = "84ed2fbe7b1ff0cd96f240905758257595822df1"